name: Pull request validation

on:
  pull_request:
    branches: [dev]

jobs:
  build:
    name: Validate core functionality
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build the solution
      run: dotnet build --no-restore
    - name: Test the solution
      run: dotnet test --no-build --verbosity normal
