name: Pull request validation

on:
  pull_request:
    branches: [dev]
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Validate core functionality
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
   
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Install SonarScanner as a global tool
      run: dotnet tool install --global dotnet-sonarscanner
      
    - name: Start analyzation with SonarCloud
      run: dotnet-sonarscanner begin /k:"TryAtSoftware_Randomizer" /o:"tryatsoftware" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
   
    - name: Restore dependencies
      run: dotnet restore
    - name: Build the solution
      run: dotnet build --no-restore
    - name: Test the solution
      run: dotnet test --no-build --verbosity normal --collect="Code coverage"
    
    - name: Finalize analyzation with SonarCloud
      run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
